version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Set Environment Variables
          command: |
            echo 'export DOCKER_COMPOSE_VERSION=1.23.2' >> $BASH_ENV 
            echo 'export COMMIT=${CIRCLE_BUILD_NUM::8}' >> $BASH_ENV 
            echo 'export MAIN_REPO=https://github.com/icruzr93/microservices-ulearning.git' >> $BASH_ENV 
            echo 'export USERS=test-driven-users' >> $BASH_ENV 
            echo 'export USERS_REPO=${MAIN_REPO}#${CIRCLE_BRANCH}:services/users' >> $BASH_ENV 
            echo 'export USERS_DB=test-driven-users_db' >> $BASH_ENV 
            echo 'export USERS_DB_REPO=${MAIN_REPO}#${CIRCLE_BRANCH}:services/users/project/db' >> $BASH_ENV 
            echo 'export CLIENT=test-driven-client' >> $BASH_ENV  
            echo 'export CLIENT_REPO=${MAIN_REPO}#${CIRCLE_BRANCH}:services/client' >> $BASH_ENV  
            echo 'export SWAGGER=test-driven-swagger' >> $BASH_ENV  
            echo 'export SWAGGER_REPO=${MAIN_REPO}#${CIRCLE_BRANCH}:services/swagger' >> $BASH_ENV  
            echo 'export EXERCISES=test-driven-exercises' >> $BASH_ENV  
            echo 'export EXERCISES_REPO=${MAIN_REPO}#${CIRCLE_BRANCH}:services/exercises' >> $BASH_ENV  
            echo 'export EXERCISES_DB=test-driven-exercises_db' >> $BASH_ENV  
            echo 'export EXERCISES_DB=${MAIN_REPO}#${CIRCLE_BRANCH}:services/exercises/project/db' >> $BASH_ENV  
            echo 'export SECRET_KEY=my_precious' >> $BASH_ENV
      - run:
          name: "What branch am I on?"
          command: echo $${CIRCLE_BRANCH}
      - run:
          name: Install Docker Compose
          command: |
            sudo rm /usr/local/bin/docker-compose
            curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Configure Environment
          command: |
            echo 'export REACT_APP_USERS_SERVICE_URL=http://127.0.0.1' >> $BASH_ENV 
            echo 'export REACT_APP_EXERCISES_SERVICE_URL=http://127.0.0.1' >> $BASH_ENV 
            echo 'export REACT_APP_API_GATEWAY_URL=https://kdsh7wu1w2.execute-api.us-west-1.amazonaws.com/v1/execute' >> $BASH_ENV 
            npm install
      - run:
          name: Run CI Tests
          command: ./test-ci.sh
      - run:
          name: Push To ECR
          command: ./docker-push.sh
      - run:
          name: Deploy Staging
          command: ./docker-deploy-stage.sh
      - run:
          name: Deploy Prod
          command: ./docker-deploy-prod.sh
